apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8sazureblocktest
metadata:
  name: block-test-namespace
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod", "Service", "ServiceAccount", "Secret", "ConfigMap"]
