apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureBlockDefault
metadata:
  name: block-default-namespace
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod", "Service", "ServiceAccount", "Secret", "ConfigMap"]
